#!/bin/bash

[ ! -d build ] && mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCAPTOR_HAVE_MY_BOOL=OFF -DEVENT__DISABLE_MBEDTLS=ON -DEVENT__DISABLE_OPENSSL=NO -DEVENT__LIBRARY_TYPE=STATIC -DEVENT__DISABLE_BENCHMARK=ON -DEVENT__DISABLE_REGRESS=ON -DEVENT__DISABLE_REGRESS=ON -DEVENT__DISABLE_SAMPLES=ON -DEVENT__DISABLE_TESTS=ON ..
#cpack .. 
make
#make install